apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
  namespace: flux-system
spec:
  interval: 15m
  chart:
    spec:
      chart: cloudnative-pg
      version: "1.28.0"
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
  targetNamespace: cnpg-system
  install:
    createNamespace: true
  values:
    monitoring:
      podMonitorEnabled: true # Enables PodMonitor for metrics scraping by Prometheus
    image:
      pullPolicy: IfNotPresent
    securityContext:
      runAsNonRoot: true
      allowPrivilegeEscalation: false
    # For reliability, enable high availability
    cluster:
      instances: 3
      primaryUpdateStrategy: unsupervised
