apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:8dsyl44dI2HdyMalGvRLQdyJcd9k8Etf99sYbcrhkoFSEOFQJ9hdBg==,iv:ToVyEr0KphaIDxFTdm0oGxVb1rO97lsstqybM+e5lh8=,tag:mWznJHdq+vHeT3ctu36o4A==,type:str]
sops:
  age:
    - recipient: age1g2h59x3sfluwjzn8hfhxpx5j7sjxq7ndjnmetracdz2g0zhgngrs6uyssf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHRGJ4M00weDVkd1RCYnl5
        U3RpKy92THhqNnFFa3lYdUF4ai9rL1U4ZGdZCjJFakJ5VllLN3Y1NFFRL2plZVBu
        QStjSjc0RWhXVDl2U0VoT0UyY0pQQk0KLS0tIFozV1ZrMUlVdE03aG8zMkFyN0pS
        b3J0eVhRUjFuSmNYcHo3cnNPakN5UjAKevVEWcuc0JgmSaC3ij+Ln1m2uIyPv8YG
        iOSD2JBnlbDUPEzcy6h0CB5YA95gncGa+504EpWFTzXZuvkS9BIbmg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-17T21:52:20Z"
  mac: ENC[AES256_GCM,data:45EkFkT9COSNZ2/vLWwEXZQcbRRzdNrK7cD+dZhdSdxD291z2ybUo+iTqmm+YIeFUpef5tshkNzPTHdYYnlszTVnrjNxCF/ojRTn1cRIOu8/BAuKbONWTzoORp9edzWDO0t0u9G21GdrYUljWH/6JReXvEp+7JDFsyTcvw/wfG4=,iv:txN9GHcwKVW1RzHq4oxOzVB4nrcOrNO1S4MKhLisads=,tag:QOqgsG0A1NZYrwfph2uZIg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
