apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:24/FZKs7QsrRtg==,iv:9jwPNs3iwsABgF/IA2LiittQ6zcRKBymmJPgGjlGe1w=,tag:nwRDIy6DJ07ittwKo+ct6A==,type:str]
sops:
  age:
    - recipient: age1g2h59x3sfluwjzn8hfhxpx5j7sjxq7ndjnmetracdz2g0zhgngrs6uyssf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0M1JJczJ4cHBjVmIzMVN2
        MGFqOFYzMS83WGVXY1RhcHdnYnVLU2xtdUc4Ckg4cm1CNDROUFhhbUc3TUFUa0JF
        Zm9hZS9INEpMMGsvSm96djQ1TEdWZDAKLS0tIEhRUk43aUNzc25RVE1heG5Xakwy
        R0lBbUg1TmNLbGdBMXpjQkQwY2VpTjgK6m9LUxxzOaLJMGSK107lPcEv98/vHuYj
        L6+16ZTZF3E9vorq4zLTUvVQ5MaYM5e4T6RefeS7RCaCB7fwHbZ+9g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-14T06:18:12Z"
  mac: ENC[AES256_GCM,data:BTDMKQO4yQg7JzA+XB85vWPl1HnpYX3SDL9rgqM0hP8TzS6bTeWbUScID5g6tnu4CvIY/WF+HKRrYz3YBmNSYRP+v8x6t8o4H/RmAYxCKAYVwxFCQ3dLmA+eNjbQCu61m1XIbUHpdnHFJH0bPGwLNIuSXBpINFFT2jLgD2ztSFY=,iv:zZI3ESLdD5V8qsHfQrjs2dwBIzFnzZ1/ko0pjpbpBP0=,tag:SCUGiByYSZDrWT0fh9XO0w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
