apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:ZkbcFnesTR5rMw==,iv:ojSE9x4d40flzse0mjCIAEFlDSJFB9/MnNhQEoPDoAo=,tag:AkHEYUIkDziukPliR2/Cyw==,type:str]
sops:
  age:
    - recipient: age1g2h59x3sfluwjzn8hfhxpx5j7sjxq7ndjnmetracdz2g0zhgngrs6uyssf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Sy9kWXVhRWNIY0tFSTIv
        cWlJSFVKV0dZdGc3ZlJScUVOazd6V3orZHpZCnVkQ0VCeFFzd1BJLzBZTGxpa2Fm
        dXAvUU05T1dmSkxZSFc4QndRUXA3djAKLS0tIGNiQ3kvM1QwdFJGNW51UFlDOSt5
        aWRlcUg4S1ZtbVJrQU4vVjEzL1RXQkUKAV84UFnXHUF21ae3RBrwuYIt6NCpbap7
        I6JTRW5AKNdil2mdO9CEp3V5x/iNoVEDkrX3XP7NhI2q2kWygojTxA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-12T03:44:08Z"
  mac: ENC[AES256_GCM,data:IXnibVaPVQZ4nY/vVdadfT/mkt4OwXOGEkyeTvBTN8nWLYANc3LuACylBIcyarIji0JS6qqVHRejPWIBZt2d6w9UkfNNzL9ibL8SLCFg10kSTB4jKa+3a4DEn+zjbKaLSUZlgNFOfNKd7Xhl+1514vf0eIPA59z0rvuzLXx/KDk=,iv:9BxXHTt+vY0XJaJ9jmrHUbIKxkkpRpY3x2DIRPoULIU=,tag:uB6sTMIM77Jtse+f4oMwkw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-r2-secret
  namespace: longhorn-system
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:PQvSoe/TsDm48+cCKhZJPLkevmsS126wv6cM2SbdmlE=,iv:aBDfi4BdLdzN15Z48ZVm3SAbCbgdUafmhfwiDYF2MuU=,tag:BWLvm2dF6Z4CL21sMFj0vQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:sa1kksEJcsxAKFjADI92tu+2my8JmPB/+417ZZ6aACNpsoOenLrqOaK60QMto7u1POr/UFbFCE4IPIhRIRTNoA==,iv:gWHiUT4f22KKHqI2fojSDex4+NaPbr4aZYKNkjwCEjg=,tag:eUSny2u2yB6KU+rat63h0g==,type:str]
  AWS_ENDPOINTS: ENC[AES256_GCM,data:3c1s6MsZZU623vASHfuIKeGffZDnKzU4hHFbCxuYFb/JWoYebXaAPfdiRdgrL6ehmQggZF0FpGNmFH6j2OEYKwk=,iv:BidrUJWohGBfkvcuf6x56hlB3PaUGCJ/P56cV3f5Wh0=,tag:3/1l1AgGwV89Tp6/ux9GPw==,type:str]
sops:
  age:
    - recipient: age1g2h59x3sfluwjzn8hfhxpx5j7sjxq7ndjnmetracdz2g0zhgngrs6uyssf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Sy9kWXVhRWNIY0tFSTIv
        cWlJSFVKV0dZdGc3ZlJScUVOazd6V3orZHpZCnVkQ0VCeFFzd1BJLzBZTGxpa2Fm
        dXAvUU05T1dmSkxZSFc4QndRUXA3djAKLS0tIGNiQ3kvM1QwdFJGNW51UFlDOSt5
        aWRlcUg4S1ZtbVJrQU4vVjEzL1RXQkUKAV84UFnXHUF21ae3RBrwuYIt6NCpbap7
        I6JTRW5AKNdil2mdO9CEp3V5x/iNoVEDkrX3XP7NhI2q2kWygojTxA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-12T03:44:08Z"
  mac: ENC[AES256_GCM,data:IXnibVaPVQZ4nY/vVdadfT/mkt4OwXOGEkyeTvBTN8nWLYANc3LuACylBIcyarIji0JS6qqVHRejPWIBZt2d6w9UkfNNzL9ibL8SLCFg10kSTB4jKa+3a4DEn+zjbKaLSUZlgNFOfNKd7Xhl+1514vf0eIPA59z0rvuzLXx/KDk=,iv:9BxXHTt+vY0XJaJ9jmrHUbIKxkkpRpY3x2DIRPoULIU=,tag:uB6sTMIM77Jtse+f4oMwkw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
