apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:HzHQgHbVO7CIhg==,iv:mOSuHLRnT+FWPzIis98T7AS0OtaSKivVgtDBwSggxYo=,tag:tm7wmcPNTtyR+KyjyklFpw==,type:str]
sops:
  age:
    - recipient: age1g2h59x3sfluwjzn8hfhxpx5j7sjxq7ndjnmetracdz2g0zhgngrs6uyssf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXL1FxWjBieFhEeUc1V3p0
        RHlaYU1MVzdWTzhLdFROekpHUnhLWjVqL1Z3CkVqYUZiZXBCaEY2T2dwZXNjdW1J
        b09MSmZRVzNlblYzdW04U01GMXkyTDgKLS0tIGtSWXl5SFdsc0xLZWFWaWJJcWZB
        OTdFZ0dmTlBYbDUwdzNibHFSbThkS2sK38s4pPmzW1up4GOPiYefxgi4KRICmzyc
        7ro5LfbZkuRAwWJP2o/l7hlrGdw608HaUCGTcRBEiCHj3pQ+9xIRnw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-17T21:52:21Z"
  mac: ENC[AES256_GCM,data:Wze5HUvqV+/VaBxwCtoouH8I9d8ze+XEIsY2IF35Vo/3LyNeQFJQB1BdoQSr8nWymDStuIWvOuCSIoa2YI0wZjImBX6j1ElqhbLfTMWaffGIVQ0bXu/DZl2q2sLe09+Vj6OJKbqVk6S6hBDgdBOG6xVT5uABff25z2FEXAoXL0c=,iv:FNte+ZRzyUzC58rraL5e/BonhQARAbcXac3lk0/qwEU=,tag:W/e6JXEAEJygSQsB6onwYA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
