apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:qUc/gBQn6fwsJGFI9IW/+dRc/GG1GutKTDTdtRjUpXk=,iv:YCqWxcWQqZt2R36rad2LBBwkK7bLE7NAybeNxPYsFVA=,tag:KT+GQB3f/EIPQZQVmhtVsA==,type:str]
sops:
  age:
    - recipient: age1g2h59x3sfluwjzn8hfhxpx5j7sjxq7ndjnmetracdz2g0zhgngrs6uyssf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwekhWU0xtcVlFS3NkcFl4
        VStBL2Z4L1hoWEZheFNQdk9DRGYwZm0rd3pBCjFMWFN2aWNwZWlVcjJEbnR2NkxH
        dmpHdVVGTmlRY2NyNVUyNEJrNmdZVFkKLS0tIFk0cVY4Zmc3WTM4VS9sSFhHbnpX
        UjJkeFdjeG96T2kvT0RWNHhNenBFUjQK6EDFp++C5B+seMnAVjsGRkSFahBqiE5i
        CuCcW0etWX07y9U7StY3aqVjPDhIen3EYRcdb1LheVOHpROAKpmSSA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-17T21:52:20Z"
  mac: ENC[AES256_GCM,data:rymJgPUPxSyVX9pxpmpYUe+d8fOGsocXy3bF1AJZPeIOy3ikLWyZFIMI2BB8c1fU1mBcG/lPfqWi+2fJrR1MKobWtL3DhL5J/lLxSKxgmXGhXDqC7OdoFQrQbXyOeqCtDpj2zeMM1XKoEiw6F/mB2+gRxscFFRfvX8oXz9Zp3EU=,iv:CtyEsSP7d3z7tnfDSKGqMa66sanf13JXkDh8OMNCO18=,tag:69Wy9wJPPVaI/ENolfi3Mw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
