apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-r2-secret
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:v7ObI5qnT90KzhCRaHtjWK61T4q5UgLVdmb2WfFiMO8=,iv:o2QxFC+2NnQ7ztRYUugHmhXhPpwgXFrR6nXnccBwHrI=,tag:IbELK1hSbkFBzrWKaB1Jcw==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:sUz8VdguTcma5QR0/haQiE9dAe+m3r7Gg1OHVbmnZ1t7u3if5bivqL3Aw9hxidGEDGqyT34oS4mnAcQ9TuWYug==,iv:apbAPBruHG8QHhdgyh57AOg1mNxbEsIbKF9gxOnHZiU=,tag:8rQhdL1UWC6b9EGVLLPSCg==,type:str]
  AWS_ENDPOINTS: ENC[AES256_GCM,data:vgYJCa+y/hgBe/SSNQl08U+2vZtaxyDmeu/+mBq6J/2fYn5rAQ9PnuEmU1gfWYWUxOt/49rBP16k8ngws2ukbiI=,iv:6Y3NCGJMty0Yzo0OgShUQeJj9sjdvOTqJ9d4BDDkdNc=,tag:bw1yzyWWzHoYm1CPo9jYhw==,type:str]
sops:
  age:
    - recipient: age1g2h59x3sfluwjzn8hfhxpx5j7sjxq7ndjnmetracdz2g0zhgngrs6uyssf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBySzczRTBrUktLMzdhZWRZ
        L1UrUXdtYTRWWjJNL0xRMm02c3lTbTNjVnl3Clhub0hUc3Z5bTlIaXh5M3ZEQ0JW
        N0JLaTFwWXo0b0FWM2hHQUhvQlIxbU0KLS0tIFp1bFUxQzFMSm9vbjZQV0J4Q21j
        aFB0UlVabjVqU0VlUEs2VDllR2FoZXcKK+fJ7anYJE07WmSfC62lzJRGY3L9UDOA
        LCk2kwz+dMx4Hkh7GLEMllUzuFRBj5JzsizfptfNWjea5aASOv7rgw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-14T06:18:12Z"
  mac: ENC[AES256_GCM,data:1XO+MDz49ZsYRmAsl/8RHQyAmZ/DR14/M3l+MFFyRFTrBsisAJabf19G433YfCifOJTPZhzzcUoHi30ywVrMqOu5JCnNPDCLcdr5mibW3A+0FWJPDiXmwvACmH31E012mjezi5REoWPS/6/SwOt2hM4nHLggSyywLmz+miNrC4I=,iv:1L63IMPWb5z1m7v2tkOHG8hqoPhFwvmjTKuSE4fxzSY=,tag:k68PLPSvEBd/TpRFe5ktlw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
