apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-r2-secret
  namespace: longhorn-system
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:g9zUGW44r++sA4AJnlhcF3tywIbL8xSWoTvXJ8uvuUE=,iv:+/9qDinSYn1TFjeJU73GdO0clkWAzN0/4e7aJOYG8oo=,tag:e+CY8/EL69GxG5uBKEQMSA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:oipLLM28brpv0TxfTbNJBeT3gK2goA0MzE+ysBdpMzQNEAvCZvmPQjU5B8MRpHaatFQH9TDUIejQrK3j28RKXg==,iv:eeLx8CFRtR5m0mdduleYF0262/0vUZ2qgQGXsHLaMLw=,tag:pUGsh2xoyDHKPA7vrYlOTg==,type:str]
  AWS_ENDPOINTS: ENC[AES256_GCM,data:fWZxtvr5RJOvujSXlSEeAXr9cCvuX0FEnlW7nJrwDmGdWabrUm8h8mL2I6gB7BbWQkOvxqgR4ZW5sQSoezIjFG4=,iv:2+X6TyTtT10Ti5+b417X8i4DVWoVHZ+xrXOdr7g3tMU=,tag:WeFqQtVd6C5RSD4Z017cVg==,type:str]
sops:
  age:
    - recipient: age1g2h59x3sfluwjzn8hfhxpx5j7sjxq7ndjnmetracdz2g0zhgngrs6uyssf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBRE1pYUVHODJKbVRqM0ts
        b1N2eGtBdGkvNEcwZFBUVi94ZjdOQlRFbXg4CjZwNjR2TXA2UGcvMUdmckE4RCtU
        VCtVTCtIYjVOUTNxb2pRNmRIS3gwbTgKLS0tIDJjSkYyWjdodFpxRmpEMkdKR2pw
        bEtQbHdPemdoMmI1b2k1RkFraHp0M1UK5lgKDiilxHMob/0icYKv7u+TShheN7qX
        erPn/WS125pv9VNaCUOa/7BxTRNAuAYD7W+EzLoEZqEr5sQapwQThw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-17T19:14:45Z"
  mac: ENC[AES256_GCM,data:FE5LVk6VeBpT+n8k6NGdPi+bVzUBv8fY4B8UZwK1pWoWZ7bILk0+Qq/sYKlgIt+EOqHZn6chssptN7w9fwjb3+82br0FG4Eb9PQLELymSQBkhG9nHY1Ab/G65f9Z9vLQMpJ/gT7+s0VW93SfN5yPpFwHMuamhf94ZXNL10Pda1A=,iv:bZ1RF2RcWQJmr+NYg2QLn40h8on+UKhLqIveEKQ4SZU=,tag:F0XBcieLAe8NOla6fNs7Bg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
