apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:i+mcWn6UHrvUxmrw4QK+eadFt264KwlD04PisW/zirsKdicZ9q5YMRfQMLCnxGmjjmBip2rtqQqx7NcObNk89tQSGcHin1u7AybOxmP1EPunJXdgvKhZZmOlWLTXRM0feRsL6Sd79r+omtBheJ2lH6Sr7kwGJ82V7BTtmZnhPRJfBfKTGLsUz0/DrHgCv+NowoYxVTO1qjGF/FuXxdLv/5TLXKNehMOjDEJCNRzE2oI1QmDb,iv:laxnt/ButkAXS6x+xPGeBicoX/u95IXSX+mR2QnyIGc=,tag:8VmRdLK61LUNH0PG45w3Zw==,type:str]
sops:
  age:
    - recipient: age1g2h59x3sfluwjzn8hfhxpx5j7sjxq7ndjnmetracdz2g0zhgngrs6uyssf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnMU9uN3Qwb2lnbTdRbXBL
        VDV5TzF3VzlxS0ZrTHdVV1hrQkZwbDhDYlJNCkp4Yk85cE9kcmNEam1Tak1iZ2NR
        SUNLZ0ptSjh3VktZeXFyVmVFWSt0MDQKLS0tIEtYSzhYL0dUN0xxV20yWEcwNUs2
        OHJ5bFBkWFAvSTgzOUR0SHBwZWdHWG8KnQXUUQHZAQyK5wYnqQdtiU0hLfkMJL0Q
        5QKAAqlX3CJH8QCXtFg9dK9BMrIT9S1MH1v/VESghc4IaJmk7qxnfg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-17T21:52:21Z"
  mac: ENC[AES256_GCM,data:/O2vQa8SUCZ2UBw+kasxIIKm6ypchZ/lpnEbYHNEIP2eZmgSb0r5o/y7M/N45Va3ceAg34b+tEH5n30l/DssXzCFqJUnje4svPZ4p3+D/gU/m0OouKAJVLDhPpvnbnliHa9RnK5JJItv8zi+Y9sX9l1OX+nrt/mIard+Py508ag=,iv:Mz2daT7VSlRNsRri2v11jvhnWuFXxc6txAwbNAhW2cw=,tag:1Q3zc4lsQpB1o2sqO71h/Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
