apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:5l1W44SztltvRc31LvPaTjikKZZ64n9hQj78JjF8WEyFXfPUlCQxfA==,iv:3fgYDsWSXX3wPSgSL26OKqhZXf5tagK1IEOYm+/Yut8=,tag:O6aXs8LBShdH5w7ZUQfSTg==,type:str]
sops:
  age:
    - recipient: age1g2h59x3sfluwjzn8hfhxpx5j7sjxq7ndjnmetracdz2g0zhgngrs6uyssf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOWHdzaGY0aHpJQm9Na1Zk
        Ynd1WkdYVlErUkNmblc2ajhWZzFrZ2x1bmljCmxIbGdBR0U1Z0R0TFpqR1dTZjRB
        ek8vMGxGY3p4ZVZXRzZmQ1RML2IyclEKLS0tIEZwaXBsWkVXcFVpUHpNeGJSU2Rt
        ZDlCdzNNNk1jQTN1Q3QwVkNDTUJXZWcKf3WXs12kFqh9TjV6a43zjyvrb+5EqB6K
        oyVrzSE5Q9xoLhlqF6qyRKsPMOVAYGsxDnYTDcEjLG2DkRQ+qs2QLg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-17T21:52:20Z"
  mac: ENC[AES256_GCM,data:8GPRh1ErX7/8lVGOEDGrn7U1aSilxywEud/eq2g/Sq6dIQEx3flQbk8ck45O84Dfg2xKiOh20c1POWN94865bJ4ghUrpiwEj/ocd9G/qrW5zXXvxhy0Kyxb78OAD971Se0wJR38cj/SQgnuNLwdgSSNNc4rtDRoyssaJvZUpxXc=,iv:UWhmuCXhX8j1zCButBCzQfc51MuuAGKi6oshavDAS8o=,tag:piDC37KGII+x39XcRs/5dA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
