---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system
commonLabels:
  app.kubernetes.io/part-of: storage

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./longhorn/ks.yaml
